### ISSUE TITLE
Module not found: Can't resolve 'prop-types-exact/build/helpers/isPlainObject'

### ISSUE THREAD

**Issue by april-duong** [ljharb/prop-types-exact#18]
Just recently getting this error on all our builds `Module not found: Can't resolve 'prop-types-exact/build/helpers/isPlainObject'`. Using `airbnb-prop-types` 2.16.0 so we can't downgrade to 1.2.0 as it's not a direct dependency

**Comment by xavier-tobin-myob** [comment]
We had this issue too in our Storybook Webpack5 compilation, which relied on `airbnb-prop-types`. You can still fix this even if it's not a direct dependency. Add/update this in your `resolutions` in `package.json` - this worked for us:

```json
  "resolutions": {
    ...
    "prop-types-exact": "1.2.0"
  },
```

**Comment by RichardTMiles** [comment]
You really managed to break the internet. `airbnb-prop-types` uses this package, and imports this path.

**Comment by ljharb** [comment]
@RichardTMiles the snark isn't helpful.

The context, however, is. I'll publish a fix shortly.

**Comment by ljharb** [comment]
Try v1.2.3 of prop-types-exact, and lmk if that's sufficient.

**Comment by ljharb** [comment]
whoops, published too quick. v1.2.4 is now out, give it a shot?

**Comment by RichardTMiles** [comment]
That worked! Thanks for getting fixing this so quickly :)

**Comment by RichardTMiles** [comment]
As a side note, if you're looking to drop that specific implementation (or move the implementation location), a `major` version bump should keep everything groovy.

**Comment by april-duong** [comment]
Thanks @ljharb it's working now

**Comment by ljharb** [comment]
@RichardTMiles yes, thanks, i'm aware of how semver works :-) i just forgot that airbnb-prop-types was deep-importing that path. I'm going to add a test to prevent that mistake in the future.
