### ISSUE TITLE
unknown props found: key

### ISSUE THREAD

**Issue by tonymarklove** [ljharb/prop-types-exact#19]
I'm surprised if no one else has reported this, so perhaps I'm doing something odd, but I am getting the warning `unknown props found: key` on several React components that are used in lists. The `key`  prop is, of course, required when components are used in a list, and `prop-types-exact` used to be fine with this, but recently starting displaying the warning.

From what I can tell, the issue is caused by the change from using `Object.keys(props)` to using `ownKeys(props)` in this commit:

https://github.com/ljharb/prop-types-exact/commit/5a182fdc26b630fd20a917c35aefa249b20bacfb#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556R40

My guess it that React must mark the `key` prop as non-enumerable, so `Object.keys` didn't return it but `ownKeys` does.

**Comment by ljharb** [comment]
It hasn't been reported presumably because only 28% of users have upgraded beyond v1.2.0. Thanks, I'll look into it.

**Comment by ljharb** [comment]
v1.2.5 released.

**Comment by tonymarklove** [comment]
@ljharb thanks for the quick response! 1.2.5 fixes the warnings for me. 🙏
